apiVersion: v1
kind: Service
metadata:
  name: mooc-grafana-server
  namespace: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: mooc-grafana
  ports:
    - name: grafana-server
      port: 9091
      targetPort: 3000
