apiVersion: v1
kind: Service
metadata:
  name: todo-backend-external
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: todo-backend
  ports:
    - name: http
      port: 9092
      targetPort: 8001
      protocol: TCP
